# Generated by Django 3.0.2 on 2020-03-21 13:27

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0002_accesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+4917642071228', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
