# Generated by Django 3.0.2 on 2020-03-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0004_contactperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactperson',
            name='intensity',
            field=models.IntegerField(choices=[(1, 'Gering'), (0, 'Mittelstark'), (-1, 'Hoch')], default=1),
        ),
    ]
