# Generated by Django 3.0.2 on 2020-03-21 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0007_auto_20200321_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='citizen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_token', to='citizens.Citizen'),
        ),
    ]
