# Generated by Django 3.0.2 on 2020-03-21 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0002_accesstoken'),
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='Anonym', max_length=30),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(choices=[(1, 'Positive'), (0, 'Negative'), (-1, 'Pending')], default=-1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='citizens.Citizen')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examined_tests', to=settings.AUTH_USER_MODEL)),
                ('test_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissioned_tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
